//Generated by TurboLink CodeGenerator, do not edit!
#include "SSroCharacter/CharacterMessage.h"
#include "SSroCharacter/CharacterMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterGetCharacterRequest, ::sro::character::GetCharacterRequest)
DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterGetCharactersRequest, ::sro::character::GetCharactersRequest)
DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterGetUserCharactersRequest, ::sro::character::GetUserCharactersRequest)
DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterEditCharacterRequest, ::sro::character::EditCharacterRequest)
DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterCreateCharacterRequest, ::sro::character::CreateCharacterRequest)
DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterCharacter, ::sro::character::Character)
DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterCharacters, ::sro::character::Characters)
DEFINE_JSON_FUNCTIONS(FGrpcSroCharacterAddPlayTimeRequest, ::sro::character::AddPlayTimeRequest)

FGrpcSroCharacterEditCharacterRequest UGrpcSroCharacterEditCharacterRequestHelperLibrary::MakeEditCharacterRequest( 
    FGrpcGoogleProtobufFieldMask Mask, FGrpcSroCharacterCharacter Character 
)
{
    FGrpcSroCharacterEditCharacterRequest EditCharacterRequest;
    EditCharacterRequest.Mask = Mask;
    EditCharacterRequest.Character = MakeShareable(new FGrpcSroCharacterCharacter(Character));

    return EditCharacterRequest;
}

void UGrpcSroCharacterEditCharacterRequestHelperLibrary::BreakEditCharacterRequest(const FGrpcSroCharacterEditCharacterRequest& EditCharacterRequest,  
    FGrpcGoogleProtobufFieldMask& Mask, FGrpcSroCharacterCharacter& Character 
)
{
    Mask = EditCharacterRequest.Mask;
    if(EditCharacterRequest.Character.Get()) 
    {
        Character = *(EditCharacterRequest.Character.Get());
    }
}

