//Generated by TurboLink CodeGenerator, do not edit!
#include "SSroCharacter/InventoryService.h"
#include "SSroCharacter/InventoryClient.h"
#include "InventoryService_Private.h"
#include "InventoryMarshaling.h"
#include "SGoogleApi/AnnotationsMarshaling.h"
#include "SGoogleProtobuf/FieldMaskMarshaling.h"
#include "TurboLinkGrpcManager_Private.h"
#include "TurboLinkGrpcUtilities.h"

UInventoryService::UInventoryService()
	: d(new UInventoryService::Private())
{
}

UInventoryService::~UInventoryService()
{
	delete d;
}

void UInventoryService::Connect()
{
	FString serviceEndPoint = UTurboLinkGrpcUtilities::GetTurboLinkGrpcConfig()->GetServiceEndPoint(TEXT("InventoryService"));
	UE_LOG(LogTurboLink, Warning, TEXT("Connect to InventoryService: '%s'"), *serviceEndPoint);

	if (d->Channel == nullptr) {
		d->Channel = TurboLinkManager->d->CreateServiceChannel(TCHAR_TO_UTF8(*serviceEndPoint), this);
	}
	if (d->Stub == nullptr) {
		d->Stub = sro::character::InventoryService::NewStub(d->Channel->RpcChannel);
	}

	grpc_connectivity_state currentChannelState = d->Channel->RpcChannel->GetState(true);
	if (OnServiceStateChanged.IsBound())
	{
		OnServiceStateChanged.Broadcast(UTurboLinkGrpcManager::Private::GrpcStateToServiceState(currentChannelState));
	}
}

EGrpcServiceState UInventoryService::GetServiceState() const
{
	if (d->Channel == nullptr) return EGrpcServiceState::NotCreate;

	auto rpcChannelState = d->Channel->RpcChannel->GetState(false);
	return UTurboLinkGrpcManager::Private::GrpcStateToServiceState(rpcChannelState);
}

UInventoryServiceClient* UInventoryService::MakeClient()
{
	auto client = UGrpcService::MakeClient<UInventoryServiceClient>();
	return client;
}

void UInventoryService::Shutdown()
{
	Super::Shutdown();
	d->Stub = nullptr;
	if (d->Channel != nullptr) {
		TurboLinkManager->d->RemoveServiceChannel(d->Channel, this);
		d->Channel = nullptr;
	}
}

void UInventoryService::CallGetInventory(const FGrpcSroCharacterGetInventoryRequest& Request, FGetInventoryResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UInventoryServiceGetInventoryLambdaWrapper* lambdaWrapper = NewObject<UInventoryServiceGetInventoryLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitGetInventory();
	InnerClient->OnGetInventoryResponse.AddUniqueDynamic(lambdaWrapper, &UInventoryServiceGetInventoryLambdaWrapper::OnResponse);
	InnerClient->GetInventory(lambdaWrapper->Handle, Request, MetaData);
}
