//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SSroGameserver/ConnectionMessage.h"
#include "TurboLinkGrpcContext.h"
#include "sro/gameserver/connection.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::sro::gameserver::ConnectGameServerResponse* in, FGrpcSroGameserverConnectGameServerResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGameserverConnectGameServerResponse* in, ::sro::gameserver::ConnectGameServerResponse* out);

void GRPC_TO_TURBOLINK(const ::sro::gameserver::VerifyConnectRequest* in, FGrpcSroGameserverVerifyConnectRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGameserverVerifyConnectRequest* in, ::sro::gameserver::VerifyConnectRequest* out);

void GRPC_TO_TURBOLINK(const ::sro::gameserver::ConnectionStatus* in, FGrpcSroGameserverConnectionStatus* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGameserverConnectionStatus* in, ::sro::gameserver::ConnectionStatus* out);

void GRPC_TO_TURBOLINK(const ::sro::gameserver::TransferPlayerRequest* in, FGrpcSroGameserverTransferPlayerRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGameserverTransferPlayerRequest* in, ::sro::gameserver::TransferPlayerRequest* out);

typedef grpc::ClientAsyncResponseReader<::sro::gameserver::ConnectGameServerResponse> ConnectionService_ConnectGameServer_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::TargetId> ConnectionService_VerifyConnect_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gameserver::ConnectGameServerResponse> ConnectionService_TransferPlayer_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gameserver::ConnectionStatus> ConnectionService_IsCharacterPlaying_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gameserver::ConnectionStatus> ConnectionService_IsUserPlaying_ReaderWriter;
