//Generated by TurboLink CodeGenerator, do not edit!
#include "DataMarshaling.h"
#include "SGoogleApi/AnnotationsMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "SSro/GlobalsMarshaling.h"

void GRPC_TO_TURBOLINK(const ::sro::gameserver::GameServerDetails* in, FGrpcSroGameserverGameServerDetails* out)
{
    out->Count=in->count();
}

void TURBOLINK_TO_GRPC(const FGrpcSroGameserverGameServerDetails* in, ::sro::gameserver::GameServerDetails* out)
{
    out->set_count(in->Count);
}

