//Generated by TurboLink CodeGenerator, do not edit!
#include "DataService_Private.h"

void UGameServerDataServiceGetGameServerDetailsLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroGameserverGameServerDetails& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetGameServerDetailsResponse.RemoveDynamic(this, &UGameServerDataServiceGetGameServerDetailsLambdaWrapper::OnResponse);
}

