//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SSro/BusMessage.h"
#include "BusClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBusServiceResetReaderBusResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroResetBusResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBusServiceResetWriterBusResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroResetBusResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UBusServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnBusServiceResetReaderBusResponse OnResetReaderBusResponse;

	UPROPERTY(BlueprintAssignable)
	FOnBusServiceResetWriterBusResponse OnResetWriterBusResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitResetReaderBus();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void ResetReaderBus(FGrpcContextHandle Handle, const FGrpcSroBusTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitResetWriterBus();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void ResetWriterBus(FGrpcContextHandle Handle, const FGrpcSroBusTarget& Request, TMap<FString, FString>& MetaData);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

