//Generated by TurboLink CodeGenerator, do not edit!
#include "BusService_Private.h"

void UBusServiceResetReaderBusLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroResetBusResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnResetReaderBusResponse.RemoveDynamic(this, &UBusServiceResetReaderBusLambdaWrapper::OnResponse);
}

void UBusServiceResetWriterBusLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroResetBusResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnResetWriterBusResponse.RemoveDynamic(this, &UBusServiceResetWriterBusLambdaWrapper::OnResponse);
}

