// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sro/bus.proto
#ifndef GRPC_sro_2fbus_2eproto__INCLUDED
#define GRPC_sro_2fbus_2eproto__INCLUDED

#include "sro/bus.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sro {

class BusService final {
 public:
  static constexpr char const* service_full_name() {
    return "sro.BusService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::sro::ResetBusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>> AsyncResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>>(AsyncResetReaderBusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>> PrepareAsyncResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>>(PrepareAsyncResetReaderBusRaw(context, request, cq));
    }
    virtual ::grpc::Status ResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::sro::ResetBusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>> AsyncResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>>(AsyncResetWriterBusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>> PrepareAsyncResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>>(PrepareAsyncResetWriterBusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>* AsyncResetReaderBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>* PrepareAsyncResetReaderBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>* AsyncResetWriterBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::ResetBusResponse>* PrepareAsyncResetWriterBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::sro::ResetBusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>> AsyncResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>>(AsyncResetReaderBusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>> PrepareAsyncResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>>(PrepareAsyncResetReaderBusRaw(context, request, cq));
    }
    ::grpc::Status ResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::sro::ResetBusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>> AsyncResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>>(AsyncResetWriterBusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>> PrepareAsyncResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>>(PrepareAsyncResetWriterBusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, std::function<void(::grpc::Status)>) override;
      void ResetReaderBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, std::function<void(::grpc::Status)>) override;
      void ResetWriterBus(::grpc::ClientContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>* AsyncResetReaderBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>* PrepareAsyncResetReaderBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>* AsyncResetWriterBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::ResetBusResponse>* PrepareAsyncResetWriterBusRaw(::grpc::ClientContext* context, const ::sro::BusTarget& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ResetReaderBus_;
    const ::grpc::internal::RpcMethod rpcmethod_ResetWriterBus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ResetReaderBus(::grpc::ServerContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response);
    virtual ::grpc::Status ResetWriterBus(::grpc::ServerContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ResetReaderBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ResetReaderBus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ResetReaderBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetReaderBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetReaderBus(::grpc::ServerContext* context, ::sro::BusTarget* request, ::grpc::ServerAsyncResponseWriter< ::sro::ResetBusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ResetWriterBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ResetWriterBus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ResetWriterBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetWriterBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetWriterBus(::grpc::ServerContext* context, ::sro::BusTarget* request, ::grpc::ServerAsyncResponseWriter< ::sro::ResetBusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ResetReaderBus<WithAsyncMethod_ResetWriterBus<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ResetReaderBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ResetReaderBus() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sro::BusTarget, ::sro::ResetBusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response) { return this->ResetReaderBus(context, request, response); }));}
    void SetMessageAllocatorFor_ResetReaderBus(
        ::grpc::MessageAllocator< ::sro::BusTarget, ::sro::ResetBusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sro::BusTarget, ::sro::ResetBusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ResetReaderBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetReaderBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetReaderBus(
      ::grpc::CallbackServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ResetWriterBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ResetWriterBus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::sro::BusTarget, ::sro::ResetBusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sro::BusTarget* request, ::sro::ResetBusResponse* response) { return this->ResetWriterBus(context, request, response); }));}
    void SetMessageAllocatorFor_ResetWriterBus(
        ::grpc::MessageAllocator< ::sro::BusTarget, ::sro::ResetBusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sro::BusTarget, ::sro::ResetBusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ResetWriterBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetWriterBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetWriterBus(
      ::grpc::CallbackServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ResetReaderBus<WithCallbackMethod_ResetWriterBus<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ResetReaderBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ResetReaderBus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ResetReaderBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetReaderBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ResetWriterBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ResetWriterBus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ResetWriterBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetWriterBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ResetReaderBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ResetReaderBus() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ResetReaderBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetReaderBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetReaderBus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ResetWriterBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ResetWriterBus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ResetWriterBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetWriterBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestResetWriterBus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ResetReaderBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ResetReaderBus() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ResetReaderBus(context, request, response); }));
    }
    ~WithRawCallbackMethod_ResetReaderBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetReaderBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetReaderBus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ResetWriterBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ResetWriterBus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ResetWriterBus(context, request, response); }));
    }
    ~WithRawCallbackMethod_ResetWriterBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ResetWriterBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ResetWriterBus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ResetReaderBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ResetReaderBus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sro::BusTarget, ::sro::ResetBusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sro::BusTarget, ::sro::ResetBusResponse>* streamer) {
                       return this->StreamedResetReaderBus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ResetReaderBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ResetReaderBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedResetReaderBus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sro::BusTarget,::sro::ResetBusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ResetWriterBus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ResetWriterBus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sro::BusTarget, ::sro::ResetBusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sro::BusTarget, ::sro::ResetBusResponse>* streamer) {
                       return this->StreamedResetWriterBus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ResetWriterBus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ResetWriterBus(::grpc::ServerContext* /*context*/, const ::sro::BusTarget* /*request*/, ::sro::ResetBusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedResetWriterBus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sro::BusTarget,::sro::ResetBusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ResetReaderBus<WithStreamedUnaryMethod_ResetWriterBus<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ResetReaderBus<WithStreamedUnaryMethod_ResetWriterBus<Service > > StreamedService;
};

}  // namespace sro


#endif  // GRPC_sro_2fbus_2eproto__INCLUDED
