//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "ConnectionMessage.h"
#include "ConnectionNode.generated.h"

class UConnectionService;
class UConnectionServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceConnectGameServer : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceConnectGameServerDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverConnectGameServerResponse&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService ConnectGameServer"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceConnectGameServer* ConnectGameServer(UObject* WorldContextObject, const FGrpcSroTargetId& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceConnectGameServerDelegate OnConnectGameServerResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceConnectGameServerDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	TObjectPtr<UConnectionService> ConnectionService;
	
	UPROPERTY()
	TObjectPtr<UConnectionServiceClient> ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroTargetId Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGameserverConnectGameServerResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceVerifyConnect : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceVerifyConnectDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroTargetId&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService VerifyConnect"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceVerifyConnect* VerifyConnect(UObject* WorldContextObject, const FGrpcSroGameserverVerifyConnectRequest& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceVerifyConnectDelegate OnVerifyConnectResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceVerifyConnectDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	TObjectPtr<UConnectionService> ConnectionService;
	
	UPROPERTY()
	TObjectPtr<UConnectionServiceClient> ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroGameserverVerifyConnectRequest Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroTargetId& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceTransferPlayer : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceTransferPlayerDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverConnectGameServerResponse&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService TransferPlayer"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceTransferPlayer* TransferPlayer(UObject* WorldContextObject, const FGrpcSroGameserverTransferPlayerRequest& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceTransferPlayerDelegate OnTransferPlayerResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceTransferPlayerDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	TObjectPtr<UConnectionService> ConnectionService;
	
	UPROPERTY()
	TObjectPtr<UConnectionServiceClient> ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroGameserverTransferPlayerRequest Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGameserverConnectGameServerResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceIsCharacterPlaying : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceIsCharacterPlayingDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverConnectionStatus&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService IsCharacterPlaying"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceIsCharacterPlaying* IsCharacterPlaying(UObject* WorldContextObject, const FGrpcSroTargetId& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceIsCharacterPlayingDelegate OnIsCharacterPlayingResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceIsCharacterPlayingDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	TObjectPtr<UConnectionService> ConnectionService;
	
	UPROPERTY()
	TObjectPtr<UConnectionServiceClient> ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroTargetId Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGameserverConnectionStatus& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceIsUserPlaying : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceIsUserPlayingDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverConnectionStatus&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService IsUserPlaying"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceIsUserPlaying* IsUserPlaying(UObject* WorldContextObject, const FGrpcSroTargetId& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceIsUserPlayingDelegate OnIsUserPlayingResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceIsUserPlayingDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	TObjectPtr<UConnectionService> ConnectionService;
	
	UPROPERTY()
	TObjectPtr<UConnectionServiceClient> ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroTargetId Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGameserverConnectionStatus& Response);

	void Shutdown();
};
