//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SSroGameserver/DimensionMessage.h"
#include "DimensionClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDimensionServiceGetDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDimensionServiceGetDimensionsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverDimensions&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDimensionServiceCreateDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDimensionServiceDuplicateDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDimensionServiceEditDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDimensionServiceDeleteDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnDimensionServiceGameServerUpdateResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGameserverGameServerUpdateResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UDimensionServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnDimensionServiceGetDimensionResponse OnGetDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDimensionServiceGetDimensionsResponse OnGetDimensionsResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDimensionServiceCreateDimensionResponse OnCreateDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDimensionServiceDuplicateDimensionResponse OnDuplicateDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDimensionServiceEditDimensionResponse OnEditDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDimensionServiceDeleteDimensionResponse OnDeleteDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnDimensionServiceGameServerUpdateResponse OnGameServerUpdateResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetDimension(FGrpcContextHandle Handle, const FGrpcSroTargetId& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetDimensions();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetDimensions(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCreateDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void CreateDimension(FGrpcContextHandle Handle, const FGrpcSroGameserverCreateDimensionRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDuplicateDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void DuplicateDimension(FGrpcContextHandle Handle, const FGrpcSroGameserverDuplicateDimensionRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitEditDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void EditDimension(FGrpcContextHandle Handle, const FGrpcSroGameserverEditDimensionRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDeleteDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void DeleteDimension(FGrpcContextHandle Handle, const FGrpcSroTargetId& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGameServerUpdate();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GameServerUpdate(FGrpcContextHandle Handle, const FGrpcSroTargetId& Request, TMap<FString, FString>& MetaData);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

