// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sro/gameserver/data.proto

#include "sro/gameserver/data.pb.h"
#include "sro/gameserver/data.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sro {
namespace gameserver {

static const char* GameServerDataService_method_names[] = {
  "/sro.gameserver.GameServerDataService/GetGameServerDetails",
};

std::unique_ptr< GameServerDataService::Stub> GameServerDataService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GameServerDataService::Stub> stub(new GameServerDataService::Stub(channel, options));
  return stub;
}

GameServerDataService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetGameServerDetails_(GameServerDataService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GameServerDataService::Stub::GetGameServerDetails(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::sro::gameserver::GameServerDetails* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::sro::gameserver::GameServerDetails, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetGameServerDetails_, context, request, response);
}

void GameServerDataService::Stub::async::GetGameServerDetails(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::sro::gameserver::GameServerDetails* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::sro::gameserver::GameServerDetails, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGameServerDetails_, context, request, response, std::move(f));
}

void GameServerDataService::Stub::async::GetGameServerDetails(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::sro::gameserver::GameServerDetails* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGameServerDetails_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sro::gameserver::GameServerDetails>* GameServerDataService::Stub::PrepareAsyncGetGameServerDetailsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sro::gameserver::GameServerDetails, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetGameServerDetails_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sro::gameserver::GameServerDetails>* GameServerDataService::Stub::AsyncGetGameServerDetailsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetGameServerDetailsRaw(context, request, cq);
  result->StartCall();
  return result;
}

GameServerDataService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GameServerDataService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GameServerDataService::Service, ::google::protobuf::Empty, ::sro::gameserver::GameServerDetails, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GameServerDataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::sro::gameserver::GameServerDetails* resp) {
               return service->GetGameServerDetails(ctx, req, resp);
             }, this)));
}

GameServerDataService::Service::~Service() {
}

::grpc::Status GameServerDataService::Service::GetGameServerDetails(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::sro::gameserver::GameServerDetails* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sro
}  // namespace gameserver

