#if defined(_MSC_VER)
  #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
  #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
  #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
  #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
  #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
  #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
  #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
  #pragma warning (disable:4307) // 'operator' : integral constant overflow
  #pragma warning (disable:4309) // 'conversion' : truncation of constant value
  #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
  #pragma warning (disable:4355) // 'this' : used in base member initializer list
  #pragma warning (disable:4506) // no definition for inline function 'function'
  #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
  #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sro/gamedata/gamedata.proto

#include "sro/gamedata/gamedata.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace sro {
namespace gamedata {
}  // namespace gamedata
}  // namespace sro
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_sro_2fgamedata_2fgamedata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_sro_2fgamedata_2fgamedata_2eproto = nullptr;
const ::uint32_t TableStruct_sro_2fgamedata_2fgamedata_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_sro_2fgamedata_2fgamedata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\033sro/gamedata/gamedata.proto\022\014sro.gamed"
    "ata2\021\n\017GameDataServiceB7Z5github.com/Sha"
    "tteredRealms/gamedata-service/pkg/pb;pbb"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_sro_2fgamedata_2fgamedata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sro_2fgamedata_2fgamedata_2eproto = {
    false,
    false,
    127,
    descriptor_table_protodef_sro_2fgamedata_2fgamedata_2eproto,
    "sro/gamedata/gamedata.proto",
    &descriptor_table_sro_2fgamedata_2fgamedata_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_sro_2fgamedata_2fgamedata_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_sro_2fgamedata_2fgamedata_2eproto,
    file_level_service_descriptors_sro_2fgamedata_2fgamedata_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sro_2fgamedata_2fgamedata_2eproto_getter() {
  return &descriptor_table_sro_2fgamedata_2fgamedata_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sro_2fgamedata_2fgamedata_2eproto(&descriptor_table_sro_2fgamedata_2fgamedata_2eproto);
namespace sro {
namespace gamedata {
// @@protoc_insertion_point(namespace_scope)
}  // namespace gamedata
}  // namespace sro
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
