//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SSroGamedata/GamedataService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "sro/gamedata/gamedata.grpc.pb.h"

class UGameDataService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::sro::gamedata::GameDataService::Stub> Stub;
};


